trigger:
- master
- azure-pipelines

stages:
  - stage:
    jobs:
      - job: 'Build_PyInstaller_Windows'
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'
      
      - job: 'Build_PyInstaller_Mac_OSX'
        pool: 
          vmImage: 'macOS-latest'
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'
