trigger:
- master
- azure-pipelines

stages:
  - stage:
    jobs:
      - job: 'Build_PyInstaller_Windows'
        pool: 
          vmImage: 'windows-latest'
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'
        - script: python -m pip install --upgrade pip
          displayName: 'update pip'
        - script: python -m pip install wheel
          displayName: 'install wheel'
        - script: python -m pip install pyinstaller
          displayName: 'install pyinstaller'
        - script: python -m pip install -r ./requirements.txt
          displayName: 'install HerbASAP requirements'
        - script: pyinstaller ./docs/build_docs/win-build.spec
          displayName: 'build HerbASAP pyinstaller'

      - job: 'Build_PyInstaller_Mac_OSX'
        pool: 
          vmImage: 'macOS-latest'
        steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'
        - script: python -m pip install --upgrade pip
          displayName: 'update pip'
        - script: python -m pip install wheel
          displayName: 'update wheel'
        - script: python -m pip install pyinstaller
          displayName: 'install pyinstaller'
        - script: python -m pip install -r ./requirements.txt
          displayName: 'install HerbASAP requirements'
        - script: pyinstaller ./docs/build_docs/macos-build.spec
          displayName: 'build HerbASAP pyinstaller'
