# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/postProcessingUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.autoPostProcessingTab = QtWidgets.QWidget()
        self.autoPostProcessingTab.setObjectName("autoPostProcessingTab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.autoPostProcessingTab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_close = QtWidgets.QPushButton(self.autoPostProcessingTab)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_beginMonitoring = QtWidgets.QPushButton(self.autoPostProcessingTab)
        self.pushButton_beginMonitoring.setObjectName("pushButton_beginMonitoring")
        self.horizontalLayout_2.addWidget(self.pushButton_beginMonitoring)
        self.gridLayout_16.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.pushButton_testFunction = QtWidgets.QPushButton(self.autoPostProcessingTab)
        self.pushButton_testFunction.setObjectName("pushButton_testFunction")
        self.gridLayout_16.addWidget(self.pushButton_testFunction, 1, 0, 1, 1)
        self.tabWidget.addTab(self.autoPostProcessingTab, "")
        self.monitorFolderTab = QtWidgets.QWidget()
        self.monitorFolderTab.setObjectName("monitorFolderTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.monitorFolderTab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.monitor_scrollArea = QtWidgets.QScrollArea(self.monitorFolderTab)
        self.monitor_scrollArea.setWidgetResizable(True)
        self.monitor_scrollArea.setObjectName("monitor_scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 663, 513))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_inputSettings = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_inputSettings.setCheckable(False)
        self.group_inputSettings.setObjectName("group_inputSettings")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.group_inputSettings)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_inputPath = QtWidgets.QLineEdit(self.group_inputSettings)
        self.lineEdit_inputPath.setEnabled(False)
        self.lineEdit_inputPath.setObjectName("lineEdit_inputPath")
        self.gridLayout_11.addWidget(self.lineEdit_inputPath, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_inputSettings)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.group_inputSettings)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 1, 0, 1, 1)
        self.pushButton_inputPath = QtWidgets.QPushButton(self.group_inputSettings)
        self.pushButton_inputPath.setObjectName("pushButton_inputPath")
        self.gridLayout_11.addWidget(self.pushButton_inputPath, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.group_inputSettings)
        self.group_keepUnalteredRaw = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_keepUnalteredRaw.setCheckable(True)
        self.group_keepUnalteredRaw.setObjectName("group_keepUnalteredRaw")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.group_keepUnalteredRaw)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_4 = QtWidgets.QLabel(self.group_keepUnalteredRaw)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.group_keepUnalteredRaw)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_pathUnalteredRaw = QtWidgets.QLineEdit(self.group_keepUnalteredRaw)
        self.lineEdit_pathUnalteredRaw.setEnabled(False)
        self.lineEdit_pathUnalteredRaw.setObjectName("lineEdit_pathUnalteredRaw")
        self.gridLayout_10.addWidget(self.lineEdit_pathUnalteredRaw, 1, 1, 1, 1)
        self.pushButton_pathUnalteredRaw = QtWidgets.QPushButton(self.group_keepUnalteredRaw)
        self.pushButton_pathUnalteredRaw.setObjectName("pushButton_pathUnalteredRaw")
        self.gridLayout_10.addWidget(self.pushButton_pathUnalteredRaw, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.group_keepUnalteredRaw)
        self.group_saveProcessedJpg = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_saveProcessedJpg.setCheckable(True)
        self.group_saveProcessedJpg.setObjectName("group_saveProcessedJpg")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.group_saveProcessedJpg)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_9 = QtWidgets.QLabel(self.group_saveProcessedJpg)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_pathProcessedJpg = QtWidgets.QLineEdit(self.group_saveProcessedJpg)
        self.lineEdit_pathProcessedJpg.setEnabled(False)
        self.lineEdit_pathProcessedJpg.setObjectName("lineEdit_pathProcessedJpg")
        self.gridLayout_13.addWidget(self.lineEdit_pathProcessedJpg, 1, 1, 1, 1)
        self.pushButton_pathProcessedJpg = QtWidgets.QPushButton(self.group_saveProcessedJpg)
        self.pushButton_pathProcessedJpg.setObjectName("pushButton_pathProcessedJpg")
        self.gridLayout_13.addWidget(self.pushButton_pathProcessedJpg, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.group_saveProcessedJpg)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.group_saveProcessedJpg)
        self.group_saveProcessedTIFF = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_saveProcessedTIFF.setCheckable(True)
        self.group_saveProcessedTIFF.setObjectName("group_saveProcessedTIFF")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.group_saveProcessedTIFF)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_pathProcessedTIFF = QtWidgets.QLineEdit(self.group_saveProcessedTIFF)
        self.lineEdit_pathProcessedTIFF.setEnabled(False)
        self.lineEdit_pathProcessedTIFF.setObjectName("lineEdit_pathProcessedTIFF")
        self.gridLayout_12.addWidget(self.lineEdit_pathProcessedTIFF, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.group_saveProcessedTIFF)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.group_saveProcessedTIFF)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 1, 0, 1, 1)
        self.pushButton_pathProcessedTIFF = QtWidgets.QPushButton(self.group_saveProcessedTIFF)
        self.pushButton_pathProcessedTIFF.setObjectName("pushButton_pathProcessedTIFF")
        self.gridLayout_12.addWidget(self.pushButton_pathProcessedTIFF, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.group_saveProcessedTIFF)
        self.group_saveProcessedPng = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_saveProcessedPng.setCheckable(True)
        self.group_saveProcessedPng.setObjectName("group_saveProcessedPng")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.group_saveProcessedPng)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_pathProcessedPng = QtWidgets.QLineEdit(self.group_saveProcessedPng)
        self.lineEdit_pathProcessedPng.setEnabled(False)
        self.lineEdit_pathProcessedPng.setObjectName("lineEdit_pathProcessedPng")
        self.gridLayout_14.addWidget(self.lineEdit_pathProcessedPng, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group_saveProcessedPng)
        self.label_10.setObjectName("label_10")
        self.gridLayout_14.addWidget(self.label_10, 1, 0, 1, 1)
        self.pushButton_pathProcessedPng = QtWidgets.QPushButton(self.group_saveProcessedPng)
        self.pushButton_pathProcessedPng.setObjectName("pushButton_pathProcessedPng")
        self.gridLayout_14.addWidget(self.pushButton_pathProcessedPng, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group_saveProcessedPng)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.group_saveProcessedPng)
        self.monitor_scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_15.addWidget(self.monitor_scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.monitorFolderTab, "")
        self.preferencesTab = QtWidgets.QWidget()
        self.preferencesTab.setObjectName("preferencesTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.preferencesTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.preferences_ScrollArea = QtWidgets.QScrollArea(self.preferencesTab)
        self.preferences_ScrollArea.setWidgetResizable(True)
        self.preferences_ScrollArea.setObjectName("preferences_ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 646, 975))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_selectTestImage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_selectTestImage.setObjectName("pushButton_selectTestImage")
        self.horizontalLayout_3.addWidget(self.pushButton_selectTestImage)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.group_barcodeDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_barcodeDetection.setAutoFillBackground(False)
        self.group_barcodeDetection.setFlat(False)
        self.group_barcodeDetection.setCheckable(False)
        self.group_barcodeDetection.setObjectName("group_barcodeDetection")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_barcodeDetection)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.group_renameByBarcode = QtWidgets.QGroupBox(self.group_barcodeDetection)
        self.group_renameByBarcode.setCheckable(True)
        self.group_renameByBarcode.setChecked(False)
        self.group_renameByBarcode.setObjectName("group_renameByBarcode")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_renameByBarcode)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_dupPreview = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_dupPreview.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dupPreview.setObjectName("label_dupPreview")
        self.gridLayout_3.addWidget(self.label_dupPreview, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 6, 1, 1)
        self.comboBox_dupNamingPolicy = QtWidgets.QComboBox(self.group_renameByBarcode)
        self.comboBox_dupNamingPolicy.setObjectName("comboBox_dupNamingPolicy")
        self.comboBox_dupNamingPolicy.addItem("")
        self.comboBox_dupNamingPolicy.addItem("")
        self.comboBox_dupNamingPolicy.addItem("")
        self.comboBox_dupNamingPolicy.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_dupNamingPolicy, 2, 2, 1, 3)
        self.label_preview = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_preview.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_preview.setObjectName("label_preview")
        self.gridLayout_3.addWidget(self.label_preview, 1, 0, 1, 1)
        self.spinBox_catalogDigits = QtWidgets.QSpinBox(self.group_renameByBarcode)
        self.spinBox_catalogDigits.setMinimum(1)
        self.spinBox_catalogDigits.setObjectName("spinBox_catalogDigits")
        self.gridLayout_3.addWidget(self.spinBox_catalogDigits, 0, 4, 1, 1)
        self.label_previewDisplay = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_previewDisplay.setText("")
        self.label_previewDisplay.setObjectName("label_previewDisplay")
        self.gridLayout_3.addWidget(self.label_previewDisplay, 1, 2, 1, 4)
        self.lineEdit_catalogNumberPrefix = QtWidgets.QLineEdit(self.group_renameByBarcode)
        self.lineEdit_catalogNumberPrefix.setObjectName("lineEdit_catalogNumberPrefix")
        self.gridLayout_3.addWidget(self.lineEdit_catalogNumberPrefix, 0, 2, 1, 1)
        self.label_digits = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_digits.setObjectName("label_digits")
        self.gridLayout_3.addWidget(self.label_digits, 0, 3, 1, 1)
        self.label_catalogNumberPrefix = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_catalogNumberPrefix.setObjectName("label_catalogNumberPrefix")
        self.gridLayout_3.addWidget(self.label_catalogNumberPrefix, 0, 0, 1, 1)
        self.label_dupNamingPolicy = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_dupNamingPolicy.setObjectName("label_dupNamingPolicy")
        self.gridLayout_3.addWidget(self.label_dupNamingPolicy, 2, 0, 1, 1)
        self.label_dupPreviewDisplay = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_dupPreviewDisplay.setText("")
        self.label_dupPreviewDisplay.setObjectName("label_dupPreviewDisplay")
        self.gridLayout_3.addWidget(self.label_dupPreviewDisplay, 3, 2, 1, 4)
        self.gridLayout_6.addWidget(self.group_renameByBarcode, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.group_barcodeDetection)
        self.group_blurDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_blurDetection.setObjectName("group_blurDetection")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.group_blurDetection)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_blurDetection = QtWidgets.QCheckBox(self.group_blurDetection)
        self.checkBox_blurDetection.setChecked(True)
        self.checkBox_blurDetection.setObjectName("checkBox_blurDetection")
        self.gridLayout_8.addWidget(self.checkBox_blurDetection, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 0, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.group_blurDetection)
        self.label_13.setEnabled(True)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 2, 1, 1)
        self.doubleSpinBox_blurThreshold = QtWidgets.QDoubleSpinBox(self.group_blurDetection)
        self.doubleSpinBox_blurThreshold.setEnabled(True)
        self.doubleSpinBox_blurThreshold.setDecimals(3)
        self.doubleSpinBox_blurThreshold.setMinimum(0.001)
        self.doubleSpinBox_blurThreshold.setMaximum(9.99)
        self.doubleSpinBox_blurThreshold.setSingleStep(0.001)
        self.doubleSpinBox_blurThreshold.setProperty("value", 0.008)
        self.doubleSpinBox_blurThreshold.setObjectName("doubleSpinBox_blurThreshold")
        self.gridLayout_8.addWidget(self.doubleSpinBox_blurThreshold, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.group_blurDetection)
        self.group_colorCheckerDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_colorCheckerDetection.setEnabled(False)
        self.group_colorCheckerDetection.setCheckable(False)
        self.group_colorCheckerDetection.setObjectName("group_colorCheckerDetection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_colorCheckerDetection)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_colorCheckerSize = QtWidgets.QGroupBox(self.group_colorCheckerDetection)
        self.groupBox_colorCheckerSize.setObjectName("groupBox_colorCheckerSize")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_colorCheckerSize)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.radioButton_colorCheckerLarge = QtWidgets.QRadioButton(self.groupBox_colorCheckerSize)
        self.radioButton_colorCheckerLarge.setObjectName("radioButton_colorCheckerLarge")
        self.gridLayout_17.addWidget(self.radioButton_colorCheckerLarge, 0, 1, 1, 1)
        self.radioButton_colorCheckerSmall = QtWidgets.QRadioButton(self.groupBox_colorCheckerSize)
        self.radioButton_colorCheckerSmall.setObjectName("radioButton_colorCheckerSmall")
        self.gridLayout_17.addWidget(self.radioButton_colorCheckerSmall, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem6, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_colorCheckerSize, 0, 0, 1, 1)
        self.group_verifyRotation = QtWidgets.QGroupBox(self.group_colorCheckerDetection)
        self.group_verifyRotation.setCheckable(True)
        self.group_verifyRotation.setChecked(False)
        self.group_verifyRotation.setObjectName("group_verifyRotation")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_verifyRotation)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 2, 1, 1)
        self.comboBox_colorCheckerPosition = QtWidgets.QComboBox(self.group_verifyRotation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_colorCheckerPosition.sizePolicy().hasHeightForWidth())
        self.comboBox_colorCheckerPosition.setSizePolicy(sizePolicy)
        self.comboBox_colorCheckerPosition.setObjectName("comboBox_colorCheckerPosition")
        self.comboBox_colorCheckerPosition.addItem("")
        self.comboBox_colorCheckerPosition.addItem("")
        self.comboBox_colorCheckerPosition.addItem("")
        self.comboBox_colorCheckerPosition.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_colorCheckerPosition, 0, 1, 1, 1)
        self.label_colorCheckerPosition = QtWidgets.QLabel(self.group_verifyRotation)
        self.label_colorCheckerPosition.setObjectName("label_colorCheckerPosition")
        self.gridLayout_5.addWidget(self.label_colorCheckerPosition, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.group_verifyRotation, 2, 0, 1, 1)
        self.checkBox_performWhiteBalance = QtWidgets.QCheckBox(self.group_colorCheckerDetection)
        self.checkBox_performWhiteBalance.setObjectName("checkBox_performWhiteBalance")
        self.gridLayout_4.addWidget(self.checkBox_performWhiteBalance, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.group_colorCheckerDetection)
        self.group_equipmentDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_equipmentDetection.setEnabled(False)
        self.group_equipmentDetection.setCheckable(False)
        self.group_equipmentDetection.setObjectName("group_equipmentDetection")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.group_equipmentDetection)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.group_equipmentDetection)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.doubleSpinBox_focalDistance = QtWidgets.QDoubleSpinBox(self.group_equipmentDetection)
        self.doubleSpinBox_focalDistance.setMinimum(10.0)
        self.doubleSpinBox_focalDistance.setMaximum(999.99)
        self.doubleSpinBox_focalDistance.setProperty("value", 25.5)
        self.doubleSpinBox_focalDistance.setObjectName("doubleSpinBox_focalDistance")
        self.horizontalLayout.addWidget(self.doubleSpinBox_focalDistance)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.gridLayout_7.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.checkBox_lensCorrection = QtWidgets.QCheckBox(self.group_equipmentDetection)
        self.checkBox_lensCorrection.setObjectName("checkBox_lensCorrection")
        self.gridLayout_7.addWidget(self.checkBox_lensCorrection, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.group_equipmentDetection)
        self.groupBox_gammaCorrection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_gammaCorrection.setObjectName("groupBox_gammaCorrection")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_gammaCorrection)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.doubleSpinBox_gammaValue = QtWidgets.QDoubleSpinBox(self.groupBox_gammaCorrection)
        self.doubleSpinBox_gammaValue.setMinimum(0.01)
        self.doubleSpinBox_gammaValue.setMaximum(3.0)
        self.doubleSpinBox_gammaValue.setSingleStep(0.1)
        self.doubleSpinBox_gammaValue.setProperty("value", 2.2)
        self.doubleSpinBox_gammaValue.setObjectName("doubleSpinBox_gammaValue")
        self.gridLayout_9.addWidget(self.doubleSpinBox_gammaValue, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_gammaCorrection)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_gammaCorrection)
        self.group_metaDataApplication = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_metaDataApplication.setEnabled(True)
        self.group_metaDataApplication.setCheckable(False)
        self.group_metaDataApplication.setObjectName("group_metaDataApplication")
        self.formLayout = QtWidgets.QFormLayout(self.group_metaDataApplication)
        self.formLayout.setObjectName("formLayout")
        self.checkBox_metaDataApplication = QtWidgets.QCheckBox(self.group_metaDataApplication)
        self.checkBox_metaDataApplication.setObjectName("checkBox_metaDataApplication")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.checkBox_metaDataApplication)
        self.label_collectionName = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_collectionName.setObjectName("label_collectionName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_collectionName)
        self.plainTextEdit_collectionName = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_collectionName.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_collectionName.setSizePolicy(sizePolicy)
        self.plainTextEdit_collectionName.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_collectionName.setTabChangesFocus(True)
        self.plainTextEdit_collectionName.setObjectName("plainTextEdit_collectionName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_collectionName)
        self.label_collectionIURL = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_collectionIURL.setObjectName("label_collectionIURL")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_collectionIURL)
        self.plainTextEdit_collectionURL = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_collectionURL.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_collectionURL.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhUrlCharactersOnly)
        self.plainTextEdit_collectionURL.setTabChangesFocus(True)
        self.plainTextEdit_collectionURL.setObjectName("plainTextEdit_collectionURL")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_collectionURL)
        self.label_contactName = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_contactName.setObjectName("label_contactName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_contactName)
        self.plainTextEdit_contactName = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_contactName.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_contactName.setTabChangesFocus(True)
        self.plainTextEdit_contactName.setObjectName("plainTextEdit_contactName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_contactName)
        self.label_contactEmail = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_contactEmail.setObjectName("label_contactEmail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_contactEmail)
        self.plainTextEdit_contactEmail = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_contactEmail.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_contactEmail.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhMultiLine)
        self.plainTextEdit_contactEmail.setTabChangesFocus(True)
        self.plainTextEdit_contactEmail.setObjectName("plainTextEdit_contactEmail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_contactEmail)
        self.label_copywriteLicense = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_copywriteLicense.setObjectName("label_copywriteLicense")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_copywriteLicense)
        self.plainTextEdit_copywriteLicense = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_copywriteLicense.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_copywriteLicense.setTabChangesFocus(True)
        self.plainTextEdit_copywriteLicense.setObjectName("plainTextEdit_copywriteLicense")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit_copywriteLicense)
        self.verticalLayout_2.addWidget(self.group_metaDataApplication)
        self.preferences_ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.preferences_ScrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.preferencesTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 22))
        self.menubar.setObjectName("menubar")
        self.menuFolder = QtWidgets.QMenu(self.menubar)
        self.menuFolder.setObjectName("menuFolder")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFolder.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_3.setBuddy(self.label_3)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.spinBox_catalogDigits.editingFinished.connect(MainWindow.saveSettings)
        self.comboBox_dupNamingPolicy.currentIndexChanged['QString'].connect(MainWindow.saveSettings)
        self.comboBox_colorCheckerPosition.currentTextChanged['QString'].connect(MainWindow.saveSettings)
        self.group_verifyRotation.toggled['bool'].connect(MainWindow.saveSettings)
        self.checkBox_performWhiteBalance.toggled['bool'].connect(MainWindow.saveSettings)
        self.checkBox_lensCorrection.toggled['bool'].connect(MainWindow.saveSettings)
        self.checkBox_metaDataApplication.toggled['bool'].connect(MainWindow.saveSettings)
        self.plainTextEdit_collectionName.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_collectionURL.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_contactName.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_contactEmail.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_copywriteLicense.textChanged.connect(MainWindow.saveSettings)
        self.group_keepUnalteredRaw.toggled['bool'].connect(MainWindow.saveSettings)
        self.group_saveProcessedJpg.toggled['bool'].connect(MainWindow.saveSettings)
        self.group_saveProcessedTIFF.toggled['bool'].connect(MainWindow.saveSettings)
        self.group_saveProcessedPng.toggled['bool'].connect(MainWindow.saveSettings)
        self.lineEdit_inputPath.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathUnalteredRaw.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathProcessedJpg.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathProcessedTIFF.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathProcessedPng.textChanged['QString'].connect(MainWindow.saveSettings)
        self.pushButton_inputPath.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathUnalteredRaw.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathProcessedJpg.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathProcessedTIFF.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathProcessedPng.clicked.connect(MainWindow.setFolderPath)
        self.lineEdit_catalogNumberPrefix.editingFinished.connect(MainWindow.updateCatalogNumberPreviews)
        self.spinBox_catalogDigits.editingFinished.connect(MainWindow.updateCatalogNumberPreviews)
        self.comboBox_dupNamingPolicy.currentIndexChanged['QString'].connect(MainWindow.updateCatalogNumberPreviews)
        self.pushButton_selectTestImage.clicked.connect(MainWindow.testFeatureCompatability)
        self.group_renameByBarcode.toggled['bool'].connect(MainWindow.updateCatalogNumberPreviews)
        self.pushButton_testFunction.clicked.connect(MainWindow.testFunction)
        self.doubleSpinBox_focalDistance.editingFinished.connect(MainWindow.saveSettings)
        self.checkBox_blurDetection.toggled['bool'].connect(self.doubleSpinBox_blurThreshold.setEnabled)
        self.checkBox_blurDetection.toggled['bool'].connect(self.label_13.setEnabled)
        self.radioButton_colorCheckerLarge.toggled['bool'].connect(MainWindow.saveSettings)
        self.radioButton_colorCheckerSmall.toggled['bool'].connect(MainWindow.saveSettings)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_inputPath, self.pushButton_inputPath)
        MainWindow.setTabOrder(self.pushButton_inputPath, self.group_keepUnalteredRaw)
        MainWindow.setTabOrder(self.group_keepUnalteredRaw, self.lineEdit_pathUnalteredRaw)
        MainWindow.setTabOrder(self.lineEdit_pathUnalteredRaw, self.pushButton_pathUnalteredRaw)
        MainWindow.setTabOrder(self.pushButton_pathUnalteredRaw, self.lineEdit_pathProcessedTIFF)
        MainWindow.setTabOrder(self.lineEdit_pathProcessedTIFF, self.pushButton_pathProcessedTIFF)
        MainWindow.setTabOrder(self.pushButton_pathProcessedTIFF, self.lineEdit_pathProcessedJpg)
        MainWindow.setTabOrder(self.lineEdit_pathProcessedJpg, self.pushButton_pathProcessedJpg)
        MainWindow.setTabOrder(self.pushButton_pathProcessedJpg, self.lineEdit_pathProcessedPng)
        MainWindow.setTabOrder(self.lineEdit_pathProcessedPng, self.pushButton_pathProcessedPng)
        MainWindow.setTabOrder(self.pushButton_pathProcessedPng, self.preferences_ScrollArea)
        MainWindow.setTabOrder(self.preferences_ScrollArea, self.group_barcodeDetection)
        MainWindow.setTabOrder(self.group_barcodeDetection, self.group_renameByBarcode)
        MainWindow.setTabOrder(self.group_renameByBarcode, self.lineEdit_catalogNumberPrefix)
        MainWindow.setTabOrder(self.lineEdit_catalogNumberPrefix, self.spinBox_catalogDigits)
        MainWindow.setTabOrder(self.spinBox_catalogDigits, self.group_colorCheckerDetection)
        MainWindow.setTabOrder(self.group_colorCheckerDetection, self.group_verifyRotation)
        MainWindow.setTabOrder(self.group_verifyRotation, self.checkBox_performWhiteBalance)
        MainWindow.setTabOrder(self.checkBox_performWhiteBalance, self.group_equipmentDetection)
        MainWindow.setTabOrder(self.group_equipmentDetection, self.group_metaDataApplication)
        MainWindow.setTabOrder(self.group_metaDataApplication, self.plainTextEdit_collectionName)
        MainWindow.setTabOrder(self.plainTextEdit_collectionName, self.pushButton_beginMonitoring)
        MainWindow.setTabOrder(self.pushButton_beginMonitoring, self.plainTextEdit_copywriteLicense)
        MainWindow.setTabOrder(self.plainTextEdit_copywriteLicense, self.monitor_scrollArea)
        MainWindow.setTabOrder(self.monitor_scrollArea, self.pushButton_close)
        MainWindow.setTabOrder(self.pushButton_close, self.plainTextEdit_contactEmail)
        MainWindow.setTabOrder(self.plainTextEdit_contactEmail, self.plainTextEdit_contactName)
        MainWindow.setTabOrder(self.plainTextEdit_contactName, self.plainTextEdit_collectionURL)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.pushButton_beginMonitoring.setText(_translate("MainWindow", "Begin Monitoring Folder"))
        self.pushButton_testFunction.setText(_translate("MainWindow", "testFunction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autoPostProcessingTab), _translate("MainWindow", "Auto Post Processing"))
        self.group_inputSettings.setTitle(_translate("MainWindow", "Input settings"))
        self.label_3.setText(_translate("MainWindow", "Input folder path (the location to monitor for newly captured photos)"))
        self.label_6.setText(_translate("MainWindow", "Folder"))
        self.pushButton_inputPath.setText(_translate("MainWindow", "Browse"))
        self.group_keepUnalteredRaw.setTitle(_translate("MainWindow", "Move unaltered original images after processing"))
        self.label_4.setText(_translate("MainWindow", "Destination folder path (the location to save unprocessed archive format images)"))
        self.label_7.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathUnalteredRaw.setText(_translate("MainWindow", "Browse"))
        self.group_saveProcessedJpg.setTitle(_translate("MainWindow", "Save processed Images as JPG"))
        self.label_9.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathProcessedJpg.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "Destination folder path (the location to save processed images as JPG files)"))
        self.group_saveProcessedTIFF.setTitle(_translate("MainWindow", "Save processed Images as TIFF"))
        self.label_5.setText(_translate("MainWindow", "Destination folder path (the location to save processed images as TIFF files)"))
        self.label_8.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathProcessedTIFF.setText(_translate("MainWindow", "Browse"))
        self.group_saveProcessedPng.setTitle(_translate("MainWindow", "Save processed Images as PNG"))
        self.label_10.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathProcessedPng.setText(_translate("MainWindow", "Browse"))
        self.label_12.setText(_translate("MainWindow", "Destination folder path (the location to save processed images as PNG files)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.monitorFolderTab), _translate("MainWindow", "Image Locations"))
        self.label.setText(_translate("MainWindow", "Test feature compatability"))
        self.pushButton_selectTestImage.setText(_translate("MainWindow", "Select test image"))
        self.group_barcodeDetection.setTitle(_translate("MainWindow", "Barcode detection"))
        self.group_renameByBarcode.setTitle(_translate("MainWindow", "Rename images by barcode number"))
        self.label_dupPreview.setText(_translate("MainWindow", "Preview"))
        self.comboBox_dupNamingPolicy.setItemText(0, _translate("MainWindow", "append LOWER case letter"))
        self.comboBox_dupNamingPolicy.setItemText(1, _translate("MainWindow", "append UPPER case letter"))
        self.comboBox_dupNamingPolicy.setItemText(2, _translate("MainWindow", "append Number with underscore"))
        self.comboBox_dupNamingPolicy.setItemText(3, _translate("MainWindow", "OVERWRITE original image with newest"))
        self.label_preview.setText(_translate("MainWindow", "Preview"))
        self.lineEdit_catalogNumberPrefix.setPlaceholderText(_translate("MainWindow", "ABCD"))
        self.label_digits.setText(_translate("MainWindow", "Digits"))
        self.label_catalogNumberPrefix.setText(_translate("MainWindow", "Catalog Number Prefix"))
        self.label_dupNamingPolicy.setText(_translate("MainWindow", "Duplicate naming policy"))
        self.group_blurDetection.setTitle(_translate("MainWindow", "Blur detection"))
        self.checkBox_blurDetection.setText(_translate("MainWindow", "Check images for blur"))
        self.label_13.setText(_translate("MainWindow", "Laplacian threshold"))
        self.group_colorCheckerDetection.setTitle(_translate("MainWindow", "Color checker detection"))
        self.groupBox_colorCheckerSize.setTitle(_translate("MainWindow", "Color checker size"))
        self.radioButton_colorCheckerLarge.setText(_translate("MainWindow", "Large"))
        self.radioButton_colorCheckerSmall.setText(_translate("MainWindow", "Small"))
        self.group_verifyRotation.setTitle(_translate("MainWindow", "Verify image rotation using color checker position"))
        self.comboBox_colorCheckerPosition.setItemText(0, _translate("MainWindow", "Upper right"))
        self.comboBox_colorCheckerPosition.setItemText(1, _translate("MainWindow", "Lower right"))
        self.comboBox_colorCheckerPosition.setItemText(2, _translate("MainWindow", "Lower left"))
        self.comboBox_colorCheckerPosition.setItemText(3, _translate("MainWindow", "Upper left"))
        self.label_colorCheckerPosition.setText(_translate("MainWindow", "Color checker Position"))
        self.checkBox_performWhiteBalance.setText(_translate("MainWindow", "Perform white balance using color checker"))
        self.group_equipmentDetection.setTitle(_translate("MainWindow", "Equipment detection"))
        self.label_2.setText(_translate("MainWindow", "Approximate focal distance to subject"))
        self.doubleSpinBox_focalDistance.setSuffix(_translate("MainWindow", "cm"))
        self.checkBox_lensCorrection.setText(_translate("MainWindow", "Perform Lens corrections"))
        self.groupBox_gammaCorrection.setTitle(_translate("MainWindow", "Gamma correction"))
        self.label_14.setText(_translate("MainWindow", "Gamma value:"))
        self.group_metaDataApplication.setTitle(_translate("MainWindow", "Metadata application"))
        self.checkBox_metaDataApplication.setText(_translate("MainWindow", "Apply metadata to images"))
        self.label_collectionName.setText(_translate("MainWindow", "Collection name"))
        self.label_collectionIURL.setText(_translate("MainWindow", "Collection URL"))
        self.label_contactName.setText(_translate("MainWindow", "Contact name"))
        self.label_contactEmail.setText(_translate("MainWindow", "Contact Email"))
        self.label_copywriteLicense.setText(_translate("MainWindow", "Copywrite License:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preferencesTab), _translate("MainWindow", "Processes"))
        self.menuFolder.setTitle(_translate("MainWindow", "Folder"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))


