# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/postProcessingUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, 3, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.folderMonitorTab = QtWidgets.QWidget()
        self.folderMonitorTab.setObjectName("folderMonitorTab")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.folderMonitorTab)
        self.gridLayout_22.setContentsMargins(3, 9, 3, 3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_diagnostics = QtWidgets.QFrame(self.folderMonitorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_diagnostics.sizePolicy().hasHeightForWidth())
        self.frame_diagnostics.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_diagnostics.setFont(font)
        self.frame_diagnostics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_diagnostics.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_diagnostics.setObjectName("frame_diagnostics")
        self.formLayout = QtWidgets.QFormLayout(self.frame_diagnostics)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(3, 9, 3, 3)
        self.formLayout.setObjectName("formLayout")
        self.label_35 = QtWidgets.QLabel(self.frame_diagnostics)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_processtime = QtWidgets.QLabel(self.frame_diagnostics)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_processtime.setFont(font)
        self.label_processtime.setText("")
        self.label_processtime.setObjectName("label_processtime")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_processtime)
        self.label_22 = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_barcodes = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_barcodes.setText("")
        self.label_barcodes.setObjectName("label_barcodes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_barcodes)
        self.label_18 = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_isBlurry = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_isBlurry.setText("")
        self.label_isBlurry.setObjectName("label_isBlurry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_isBlurry)
        self.label_21 = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_lapnorm = QtWidgets.QLabel(self.frame_diagnostics)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_lapnorm.setFont(font)
        self.label_lapnorm.setText("")
        self.label_lapnorm.setObjectName("label_lapnorm")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_lapnorm)
        self.label_17 = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_17.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.label_24 = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_runtime = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_runtime.setText("")
        self.label_runtime.setObjectName("label_runtime")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_runtime)
        self.label_whitergb = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_whitergb.setText("")
        self.label_whitergb.setObjectName("label_whitergb")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_whitergb)
        self.label_20 = QtWidgets.QLabel(self.frame_diagnostics)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.verticalLayout_4.addWidget(self.frame_diagnostics)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 0, 3, 1, 1)
        self.toolButton_delPreviousImage = QtWidgets.QToolButton(self.folderMonitorTab)
        self.toolButton_delPreviousImage.setEnabled(False)
        self.toolButton_delPreviousImage.setAutoFillBackground(False)
        self.toolButton_delPreviousImage.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/trash-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_delPreviousImage.setIcon(icon)
        self.toolButton_delPreviousImage.setObjectName("toolButton_delPreviousImage")
        self.gridLayout_16.addWidget(self.toolButton_delPreviousImage, 1, 3, 1, 1)
        self.label_cc_image = QtWidgets.QLabel(self.folderMonitorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cc_image.sizePolicy().hasHeightForWidth())
        self.label_cc_image.setSizePolicy(sizePolicy)
        self.label_cc_image.setMinimumSize(QtCore.QSize(0, 50))
        self.label_cc_image.setText("")
        self.label_cc_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cc_image.setObjectName("label_cc_image")
        self.gridLayout_16.addWidget(self.label_cc_image, 0, 2, 2, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_16)
        self.formGroupBox_sessionMetadata = QtWidgets.QGroupBox(self.folderMonitorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formGroupBox_sessionMetadata.sizePolicy().hasHeightForWidth())
        self.formGroupBox_sessionMetadata.setSizePolicy(sizePolicy)
        self.formGroupBox_sessionMetadata.setFocusPolicy(QtCore.Qt.TabFocus)
        self.formGroupBox_sessionMetadata.setFlat(False)
        self.formGroupBox_sessionMetadata.setCheckable(True)
        self.formGroupBox_sessionMetadata.setChecked(True)
        self.formGroupBox_sessionMetadata.setObjectName("formGroupBox_sessionMetadata")
        self.formLayout_metaData = QtWidgets.QFormLayout(self.formGroupBox_sessionMetadata)
        self.formLayout_metaData.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_metaData.setContentsMargins(3, 3, 3, 3)
        self.formLayout_metaData.setObjectName("formLayout_metaData")
        self.label_16 = QtWidgets.QLabel(self.formGroupBox_sessionMetadata)
        self.label_16.setObjectName("label_16")
        self.formLayout_metaData.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_taxonName = QtWidgets.QLineEdit(self.formGroupBox_sessionMetadata)
        self.lineEdit_taxonName.setObjectName("lineEdit_taxonName")
        self.formLayout_metaData.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_taxonName)
        self.label_19 = QtWidgets.QLabel(self.formGroupBox_sessionMetadata)
        self.label_19.setObjectName("label_19")
        self.formLayout_metaData.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_collectorName = QtWidgets.QLineEdit(self.formGroupBox_sessionMetadata)
        self.lineEdit_collectorName.setObjectName("lineEdit_collectorName")
        self.formLayout_metaData.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_collectorName)
        self.verticalLayout_4.addWidget(self.formGroupBox_sessionMetadata)
        self.gridTabWidget_sessionMonitor = QtWidgets.QTabWidget(self.folderMonitorTab)
        self.gridTabWidget_sessionMonitor.setAutoFillBackground(False)
        self.gridTabWidget_sessionMonitor.setTabPosition(QtWidgets.QTabWidget.North)
        self.gridTabWidget_sessionMonitor.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.gridTabWidget_sessionMonitor.setElideMode(QtCore.Qt.ElideNone)
        self.gridTabWidget_sessionMonitor.setDocumentMode(False)
        self.gridTabWidget_sessionMonitor.setObjectName("gridTabWidget_sessionMonitor")
        self.gridTabWidget_sessionSelect = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridTabWidget_sessionSelect.sizePolicy().hasHeightForWidth())
        self.gridTabWidget_sessionSelect.setSizePolicy(sizePolicy)
        self.gridTabWidget_sessionSelect.setObjectName("gridTabWidget_sessionSelect")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gridTabWidget_sessionSelect)
        self.gridLayout_23.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.comboBox_technician = QtWidgets.QComboBox(self.gridTabWidget_sessionSelect)
        self.comboBox_technician.setObjectName("comboBox_technician")
        self.horizontalLayout_6.addWidget(self.comboBox_technician)
        self.toolButton_editTechnicians = QtWidgets.QToolButton(self.gridTabWidget_sessionSelect)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_editTechnicians.setIcon(icon1)
        self.toolButton_editTechnicians.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_editTechnicians.setAutoRaise(False)
        self.toolButton_editTechnicians.setObjectName("toolButton_editTechnicians")
        self.horizontalLayout_6.addWidget(self.toolButton_editTechnicians)
        self.horizontalLayout_6.setStretch(1, 2)
        self.gridLayout_23.addLayout(self.horizontalLayout_6, 0, 0, 1, 5)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_rate = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_rate.setFont(font)
        self.label_rate.setScaledContents(True)
        self.label_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rate.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_rate.setObjectName("label_rate")
        self.gridLayout_20.addWidget(self.label_rate, 1, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_20.addWidget(self.label_32, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_20.addWidget(self.label_29, 0, 2, 1, 1)
        self.label_runTime = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_runTime.setFont(font)
        self.label_runTime.setScaledContents(True)
        self.label_runTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_runTime.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_runTime.setObjectName("label_runTime")
        self.gridLayout_20.addWidget(self.label_runTime, 1, 2, 1, 1)
        self.label_imgCount = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_imgCount.setFont(font)
        self.label_imgCount.setScaledContents(True)
        self.label_imgCount.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imgCount.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_imgCount.setObjectName("label_imgCount")
        self.gridLayout_20.addWidget(self.label_imgCount, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_20.addWidget(self.label_31, 0, 1, 1, 1)
        self.gridLayout_20.setColumnStretch(0, 1)
        self.gridLayout_23.addLayout(self.gridLayout_20, 1, 0, 1, 5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_toggleMonitoring = QtWidgets.QPushButton(self.gridTabWidget_sessionSelect)
        self.pushButton_toggleMonitoring.setObjectName("pushButton_toggleMonitoring")
        self.verticalLayout_6.addWidget(self.pushButton_toggleMonitoring)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.gridLayout_23.addLayout(self.verticalLayout_6, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_speedAnimal = QtWidgets.QLabel(self.gridTabWidget_sessionSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_speedAnimal.sizePolicy().hasHeightForWidth())
        self.label_speedAnimal.setSizePolicy(sizePolicy)
        self.label_speedAnimal.setText("")
        self.label_speedAnimal.setScaledContents(False)
        self.label_speedAnimal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speedAnimal.setObjectName("label_speedAnimal")
        self.gridLayout_23.addWidget(self.label_speedAnimal, 2, 2, 1, 1)
        self.gridTabWidget_sessionMonitor.addTab(self.gridTabWidget_sessionSelect, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_21.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem3, 0, 1, 1, 1)
        self.pushButton_processMulti = QtWidgets.QPushButton(self.tab)
        self.pushButton_processMulti.setObjectName("pushButton_processMulti")
        self.gridLayout_21.addWidget(self.pushButton_processMulti, 1, 1, 1, 1)
        self.pushButton_processSingle = QtWidgets.QPushButton(self.tab)
        self.pushButton_processSingle.setObjectName("pushButton_processSingle")
        self.gridLayout_21.addWidget(self.pushButton_processSingle, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridTabWidget_sessionMonitor.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.gridTabWidget_sessionMonitor)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(3, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.label_imPreview = QtWidgets.QLabel(self.folderMonitorTab)
        self.label_imPreview.setMinimumSize(QtCore.QSize(100, 1))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_imPreview.setFont(font)
        self.label_imPreview.setText("")
        self.label_imPreview.setScaledContents(False)
        self.label_imPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imPreview.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_imPreview.setObjectName("label_imPreview")
        self.horizontalLayout_5.addWidget(self.label_imPreview)
        self.horizontalLayout_5.setStretch(1, 1)
        self.gridLayout_22.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.folderMonitorTab, "")
        self.imgPathsTab = QtWidgets.QWidget()
        self.imgPathsTab.setObjectName("imgPathsTab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.imgPathsTab)
        self.gridLayout_15.setContentsMargins(3, 9, 3, 3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.monitor_scrollArea = QtWidgets.QScrollArea(self.imgPathsTab)
        self.monitor_scrollArea.setWidgetResizable(True)
        self.monitor_scrollArea.setObjectName("monitor_scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 688, 576))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group_inputSettings = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_inputSettings.setCheckable(False)
        self.group_inputSettings.setObjectName("group_inputSettings")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.group_inputSettings)
        self.gridLayout_11.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_inputPath = QtWidgets.QLineEdit(self.group_inputSettings)
        self.lineEdit_inputPath.setEnabled(False)
        self.lineEdit_inputPath.setObjectName("lineEdit_inputPath")
        self.gridLayout_11.addWidget(self.lineEdit_inputPath, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.group_inputSettings)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 1, 0, 1, 1)
        self.pushButton_inputPath = QtWidgets.QPushButton(self.group_inputSettings)
        self.pushButton_inputPath.setObjectName("pushButton_inputPath")
        self.gridLayout_11.addWidget(self.pushButton_inputPath, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_inputSettings)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.group_inputSettings)
        self.group_keepUnalteredRaw = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_keepUnalteredRaw.setCheckable(True)
        self.group_keepUnalteredRaw.setObjectName("group_keepUnalteredRaw")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.group_keepUnalteredRaw)
        self.gridLayout_10.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_7 = QtWidgets.QLabel(self.group_keepUnalteredRaw)
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_pathUnalteredRaw = QtWidgets.QLineEdit(self.group_keepUnalteredRaw)
        self.lineEdit_pathUnalteredRaw.setEnabled(False)
        self.lineEdit_pathUnalteredRaw.setObjectName("lineEdit_pathUnalteredRaw")
        self.gridLayout_10.addWidget(self.lineEdit_pathUnalteredRaw, 1, 1, 1, 1)
        self.pushButton_pathUnalteredRaw = QtWidgets.QPushButton(self.group_keepUnalteredRaw)
        self.pushButton_pathUnalteredRaw.setObjectName("pushButton_pathUnalteredRaw")
        self.gridLayout_10.addWidget(self.pushButton_pathUnalteredRaw, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.group_keepUnalteredRaw)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.group_keepUnalteredRaw)
        self.group_saveProcessedJpg = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_saveProcessedJpg.setCheckable(True)
        self.group_saveProcessedJpg.setObjectName("group_saveProcessedJpg")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.group_saveProcessedJpg)
        self.gridLayout_13.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_9 = QtWidgets.QLabel(self.group_saveProcessedJpg)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_pathProcessedJpg = QtWidgets.QLineEdit(self.group_saveProcessedJpg)
        self.lineEdit_pathProcessedJpg.setEnabled(False)
        self.lineEdit_pathProcessedJpg.setObjectName("lineEdit_pathProcessedJpg")
        self.gridLayout_13.addWidget(self.lineEdit_pathProcessedJpg, 1, 1, 1, 1)
        self.pushButton_pathProcessedJpg = QtWidgets.QPushButton(self.group_saveProcessedJpg)
        self.pushButton_pathProcessedJpg.setObjectName("pushButton_pathProcessedJpg")
        self.gridLayout_13.addWidget(self.pushButton_pathProcessedJpg, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.group_saveProcessedJpg)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.group_saveProcessedJpg)
        self.group_saveProcessedTIFF = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_saveProcessedTIFF.setCheckable(True)
        self.group_saveProcessedTIFF.setObjectName("group_saveProcessedTIFF")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.group_saveProcessedTIFF)
        self.gridLayout_12.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_pathProcessedTIFF = QtWidgets.QLineEdit(self.group_saveProcessedTIFF)
        self.lineEdit_pathProcessedTIFF.setEnabled(False)
        self.lineEdit_pathProcessedTIFF.setObjectName("lineEdit_pathProcessedTIFF")
        self.gridLayout_12.addWidget(self.lineEdit_pathProcessedTIFF, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.group_saveProcessedTIFF)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 1, 0, 1, 1)
        self.pushButton_pathProcessedTIFF = QtWidgets.QPushButton(self.group_saveProcessedTIFF)
        self.pushButton_pathProcessedTIFF.setObjectName("pushButton_pathProcessedTIFF")
        self.gridLayout_12.addWidget(self.pushButton_pathProcessedTIFF, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.group_saveProcessedTIFF)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 0, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.group_saveProcessedTIFF)
        self.group_saveProcessedPng = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.group_saveProcessedPng.setCheckable(True)
        self.group_saveProcessedPng.setObjectName("group_saveProcessedPng")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.group_saveProcessedPng)
        self.gridLayout_14.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_pathProcessedPng = QtWidgets.QLineEdit(self.group_saveProcessedPng)
        self.lineEdit_pathProcessedPng.setEnabled(False)
        self.lineEdit_pathProcessedPng.setObjectName("lineEdit_pathProcessedPng")
        self.gridLayout_14.addWidget(self.lineEdit_pathProcessedPng, 1, 1, 1, 1)
        self.pushButton_pathProcessedPng = QtWidgets.QPushButton(self.group_saveProcessedPng)
        self.pushButton_pathProcessedPng.setObjectName("pushButton_pathProcessedPng")
        self.gridLayout_14.addWidget(self.pushButton_pathProcessedPng, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.group_saveProcessedPng)
        self.label_10.setObjectName("label_10")
        self.gridLayout_14.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.group_saveProcessedPng)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem5, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.group_saveProcessedPng)
        self.monitor_scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_15.addWidget(self.monitor_scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.imgPathsTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settingsTab)
        self.gridLayout_2.setContentsMargins(3, 9, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.preferences_ScrollArea = QtWidgets.QScrollArea(self.settingsTab)
        self.preferences_ScrollArea.setWidgetResizable(True)
        self.preferences_ScrollArea.setObjectName("preferences_ScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -504, 671, 1078))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_selectTestImage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_selectTestImage.setObjectName("pushButton_selectTestImage")
        self.horizontalLayout_3.addWidget(self.pushButton_selectTestImage)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.group_barcodeDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_barcodeDetection.setAutoFillBackground(False)
        self.group_barcodeDetection.setFlat(False)
        self.group_barcodeDetection.setCheckable(False)
        self.group_barcodeDetection.setObjectName("group_barcodeDetection")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_barcodeDetection)
        self.gridLayout_6.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.group_renameByBarcode = QtWidgets.QGroupBox(self.group_barcodeDetection)
        self.group_renameByBarcode.setEnabled(True)
        self.group_renameByBarcode.setCheckable(True)
        self.group_renameByBarcode.setChecked(True)
        self.group_renameByBarcode.setObjectName("group_renameByBarcode")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_renameByBarcode)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_digits = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_digits.setEnabled(True)
        self.label_digits.setObjectName("label_digits")
        self.gridLayout_3.addWidget(self.label_digits, 0, 2, 1, 1)
        self.spinBox_catalogDigits = QtWidgets.QSpinBox(self.group_renameByBarcode)
        self.spinBox_catalogDigits.setEnabled(True)
        self.spinBox_catalogDigits.setFrame(True)
        self.spinBox_catalogDigits.setMinimum(0)
        self.spinBox_catalogDigits.setObjectName("spinBox_catalogDigits")
        self.gridLayout_3.addWidget(self.spinBox_catalogDigits, 0, 3, 1, 1)
        self.lineEdit_catalogNumberPrefix = QtWidgets.QLineEdit(self.group_renameByBarcode)
        self.lineEdit_catalogNumberPrefix.setEnabled(True)
        self.lineEdit_catalogNumberPrefix.setObjectName("lineEdit_catalogNumberPrefix")
        self.gridLayout_3.addWidget(self.lineEdit_catalogNumberPrefix, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_25.setEnabled(True)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_dupNamingPolicy = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_dupNamingPolicy.setEnabled(True)
        self.label_dupNamingPolicy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dupNamingPolicy.setObjectName("label_dupNamingPolicy")
        self.gridLayout_3.addWidget(self.label_dupNamingPolicy, 1, 0, 1, 1)
        self.label_dupPreview = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_dupPreview.setEnabled(True)
        self.label_dupPreview.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dupPreview.setObjectName("label_dupPreview")
        self.gridLayout_3.addWidget(self.label_dupPreview, 2, 0, 1, 1)
        self.comboBox_bcBackend = QtWidgets.QComboBox(self.group_renameByBarcode)
        self.comboBox_bcBackend.setEnabled(True)
        self.comboBox_bcBackend.setObjectName("comboBox_bcBackend")
        self.comboBox_bcBackend.addItem("")
        self.comboBox_bcBackend.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_bcBackend, 3, 1, 1, 3)
        self.label_catalogNumberPrefix = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_catalogNumberPrefix.setEnabled(True)
        self.label_catalogNumberPrefix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_catalogNumberPrefix.setObjectName("label_catalogNumberPrefix")
        self.gridLayout_3.addWidget(self.label_catalogNumberPrefix, 0, 0, 1, 1)
        self.label_dupPreviewDisplay = QtWidgets.QLabel(self.group_renameByBarcode)
        self.label_dupPreviewDisplay.setEnabled(True)
        self.label_dupPreviewDisplay.setText("")
        self.label_dupPreviewDisplay.setObjectName("label_dupPreviewDisplay")
        self.gridLayout_3.addWidget(self.label_dupPreviewDisplay, 2, 1, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 8, 1, 1)
        self.comboBox_dupNamingPolicy = QtWidgets.QComboBox(self.group_renameByBarcode)
        self.comboBox_dupNamingPolicy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_dupNamingPolicy.sizePolicy().hasHeightForWidth())
        self.comboBox_dupNamingPolicy.setSizePolicy(sizePolicy)
        self.comboBox_dupNamingPolicy.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_dupNamingPolicy.setObjectName("comboBox_dupNamingPolicy")
        self.comboBox_dupNamingPolicy.addItem("")
        self.comboBox_dupNamingPolicy.addItem("")
        self.comboBox_dupNamingPolicy.addItem("")
        self.comboBox_dupNamingPolicy.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_dupNamingPolicy, 1, 1, 1, 3)
        self.frame_patterns = QtWidgets.QFrame(self.group_renameByBarcode)
        self.frame_patterns.setEnabled(True)
        self.frame_patterns.setObjectName("frame_patterns")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_patterns)
        self.gridLayout_18.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.toolButton_removePattern = QtWidgets.QToolButton(self.frame_patterns)
        self.toolButton_removePattern.setEnabled(True)
        self.toolButton_removePattern.setCheckable(False)
        self.toolButton_removePattern.setAutoRaise(False)
        self.toolButton_removePattern.setObjectName("toolButton_removePattern")
        self.gridLayout_18.addWidget(self.toolButton_removePattern, 4, 2, 1, 1)
        self.listWidget_patterns = QtWidgets.QListWidget(self.frame_patterns)
        self.listWidget_patterns.setEnabled(True)
        self.listWidget_patterns.setAutoScroll(False)
        self.listWidget_patterns.setSelectionRectVisible(False)
        self.listWidget_patterns.setObjectName("listWidget_patterns")
        self.gridLayout_18.addWidget(self.listWidget_patterns, 1, 0, 1, 3)
        self.toolButton_addPattern = QtWidgets.QToolButton(self.frame_patterns)
        self.toolButton_addPattern.setEnabled(True)
        self.toolButton_addPattern.setObjectName("toolButton_addPattern")
        self.gridLayout_18.addWidget(self.toolButton_addPattern, 4, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem8, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_patterns)
        self.label_28.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_18.addWidget(self.label_28, 0, 0, 1, 3)
        self.gridLayout_3.addWidget(self.frame_patterns, 0, 7, 4, 1)
        self.gridLayout_6.addWidget(self.group_renameByBarcode, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.group_barcodeDetection)
        self.group_blurDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_blurDetection.setObjectName("group_blurDetection")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.group_blurDetection)
        self.gridLayout_8.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_15 = QtWidgets.QLabel(self.group_blurDetection)
        self.label_15.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 2, 0, 1, 2)
        self.checkBox_blurDetection = QtWidgets.QCheckBox(self.group_blurDetection)
        self.checkBox_blurDetection.setChecked(True)
        self.checkBox_blurDetection.setObjectName("checkBox_blurDetection")
        self.gridLayout_8.addWidget(self.checkBox_blurDetection, 0, 0, 1, 1)
        self.doubleSpinBox_blurThreshold = QtWidgets.QDoubleSpinBox(self.group_blurDetection)
        self.doubleSpinBox_blurThreshold.setEnabled(True)
        self.doubleSpinBox_blurThreshold.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleSpinBox_blurThreshold.setDecimals(3)
        self.doubleSpinBox_blurThreshold.setMinimum(0.001)
        self.doubleSpinBox_blurThreshold.setMaximum(9.99)
        self.doubleSpinBox_blurThreshold.setSingleStep(0.001)
        self.doubleSpinBox_blurThreshold.setProperty("value", 0.045)
        self.doubleSpinBox_blurThreshold.setObjectName("doubleSpinBox_blurThreshold")
        self.gridLayout_8.addWidget(self.doubleSpinBox_blurThreshold, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.group_blurDetection)
        self.label_13.setEnabled(True)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.group_blurDetection)
        self.group_colorCheckerDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_colorCheckerDetection.setEnabled(True)
        self.group_colorCheckerDetection.setCheckable(False)
        self.group_colorCheckerDetection.setObjectName("group_colorCheckerDetection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_colorCheckerDetection)
        self.gridLayout_4.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_colorCheckerSize = QtWidgets.QGroupBox(self.group_colorCheckerDetection)
        self.groupBox_colorCheckerSize.setEnabled(True)
        self.groupBox_colorCheckerSize.setObjectName("groupBox_colorCheckerSize")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_colorCheckerSize)
        self.gridLayout_17.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.radioButton_colorCheckerSmall = QtWidgets.QRadioButton(self.groupBox_colorCheckerSize)
        self.radioButton_colorCheckerSmall.setChecked(True)
        self.radioButton_colorCheckerSmall.setObjectName("radioButton_colorCheckerSmall")
        self.gridLayout_17.addWidget(self.radioButton_colorCheckerSmall, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem10, 0, 2, 1, 1)
        self.radioButton_colorCheckerLarge = QtWidgets.QRadioButton(self.groupBox_colorCheckerSize)
        self.radioButton_colorCheckerLarge.setObjectName("radioButton_colorCheckerLarge")
        self.gridLayout_17.addWidget(self.radioButton_colorCheckerLarge, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_colorCheckerSize, 0, 0, 1, 1)
        self.group_verifyRotation = QtWidgets.QGroupBox(self.group_colorCheckerDetection)
        self.group_verifyRotation.setEnabled(True)
        self.group_verifyRotation.setCheckable(True)
        self.group_verifyRotation.setChecked(True)
        self.group_verifyRotation.setObjectName("group_verifyRotation")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_verifyRotation)
        self.gridLayout_5.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 0, 2, 1, 1)
        self.comboBox_colorCheckerPosition = QtWidgets.QComboBox(self.group_verifyRotation)
        self.comboBox_colorCheckerPosition.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_colorCheckerPosition.sizePolicy().hasHeightForWidth())
        self.comboBox_colorCheckerPosition.setSizePolicy(sizePolicy)
        self.comboBox_colorCheckerPosition.setObjectName("comboBox_colorCheckerPosition")
        self.comboBox_colorCheckerPosition.addItem("")
        self.comboBox_colorCheckerPosition.addItem("")
        self.comboBox_colorCheckerPosition.addItem("")
        self.comboBox_colorCheckerPosition.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_colorCheckerPosition, 0, 1, 1, 1)
        self.label_colorCheckerPosition = QtWidgets.QLabel(self.group_verifyRotation)
        self.label_colorCheckerPosition.setEnabled(True)
        self.label_colorCheckerPosition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_colorCheckerPosition.setObjectName("label_colorCheckerPosition")
        self.gridLayout_5.addWidget(self.label_colorCheckerPosition, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.group_verifyRotation, 2, 0, 1, 1)
        self.checkBox_performWhiteBalance = QtWidgets.QCheckBox(self.group_colorCheckerDetection)
        self.checkBox_performWhiteBalance.setEnabled(True)
        self.checkBox_performWhiteBalance.setChecked(True)
        self.checkBox_performWhiteBalance.setObjectName("checkBox_performWhiteBalance")
        self.gridLayout_4.addWidget(self.checkBox_performWhiteBalance, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.group_colorCheckerDetection)
        self.group_equipmentDetection = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_equipmentDetection.setEnabled(True)
        self.group_equipmentDetection.setCheckable(False)
        self.group_equipmentDetection.setObjectName("group_equipmentDetection")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.group_equipmentDetection)
        self.gridLayout_7.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.group_equipmentDetection)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.doubleSpinBox_focalDistance = QtWidgets.QDoubleSpinBox(self.group_equipmentDetection)
        self.doubleSpinBox_focalDistance.setEnabled(True)
        self.doubleSpinBox_focalDistance.setMinimum(10.0)
        self.doubleSpinBox_focalDistance.setMaximum(999.99)
        self.doubleSpinBox_focalDistance.setProperty("value", 25.5)
        self.doubleSpinBox_focalDistance.setObjectName("doubleSpinBox_focalDistance")
        self.horizontalLayout.addWidget(self.doubleSpinBox_focalDistance)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.gridLayout_7.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.checkBox_lensCorrection = QtWidgets.QCheckBox(self.group_equipmentDetection)
        self.checkBox_lensCorrection.setEnabled(True)
        self.checkBox_lensCorrection.setChecked(True)
        self.checkBox_lensCorrection.setObjectName("checkBox_lensCorrection")
        self.gridLayout_7.addWidget(self.checkBox_lensCorrection, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.group_equipmentDetection)
        self.group_metaDataApplication = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.group_metaDataApplication.setEnabled(True)
        self.group_metaDataApplication.setCheckable(False)
        self.group_metaDataApplication.setObjectName("group_metaDataApplication")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.group_metaDataApplication)
        self.gridLayout_19.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.plainTextEdit_collectionName = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_collectionName.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_collectionName.setSizePolicy(sizePolicy)
        self.plainTextEdit_collectionName.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_collectionName.setTabChangesFocus(True)
        self.plainTextEdit_collectionName.setObjectName("plainTextEdit_collectionName")
        self.gridLayout_19.addWidget(self.plainTextEdit_collectionName, 1, 1, 1, 1)
        self.label_copywriteLicense = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_copywriteLicense.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_copywriteLicense.setObjectName("label_copywriteLicense")
        self.gridLayout_19.addWidget(self.label_copywriteLicense, 5, 0, 1, 1)
        self.label_collectionName = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_collectionName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_collectionName.setObjectName("label_collectionName")
        self.gridLayout_19.addWidget(self.label_collectionName, 1, 0, 1, 1)
        self.plainTextEdit_contactName = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_contactName.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_contactName.setTabChangesFocus(True)
        self.plainTextEdit_contactName.setObjectName("plainTextEdit_contactName")
        self.gridLayout_19.addWidget(self.plainTextEdit_contactName, 3, 1, 1, 1)
        self.label_contactEmail = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_contactEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_contactEmail.setObjectName("label_contactEmail")
        self.gridLayout_19.addWidget(self.label_contactEmail, 4, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem13, 1, 2, 1, 1)
        self.label_collectionIURL = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_collectionIURL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_collectionIURL.setObjectName("label_collectionIURL")
        self.gridLayout_19.addWidget(self.label_collectionIURL, 2, 0, 1, 1)
        self.plainTextEdit_copywriteLicense = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_copywriteLicense.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_copywriteLicense.setTabChangesFocus(True)
        self.plainTextEdit_copywriteLicense.setObjectName("plainTextEdit_copywriteLicense")
        self.gridLayout_19.addWidget(self.plainTextEdit_copywriteLicense, 5, 1, 1, 1)
        self.plainTextEdit_contactEmail = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_contactEmail.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_contactEmail.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhMultiLine)
        self.plainTextEdit_contactEmail.setTabChangesFocus(True)
        self.plainTextEdit_contactEmail.setObjectName("plainTextEdit_contactEmail")
        self.gridLayout_19.addWidget(self.plainTextEdit_contactEmail, 4, 1, 1, 1)
        self.label_contactName = QtWidgets.QLabel(self.group_metaDataApplication)
        self.label_contactName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_contactName.setObjectName("label_contactName")
        self.gridLayout_19.addWidget(self.label_contactName, 3, 0, 1, 1)
        self.checkBox_metaDataApplication = QtWidgets.QCheckBox(self.group_metaDataApplication)
        self.checkBox_metaDataApplication.setChecked(True)
        self.checkBox_metaDataApplication.setObjectName("checkBox_metaDataApplication")
        self.gridLayout_19.addWidget(self.checkBox_metaDataApplication, 0, 0, 1, 2)
        self.plainTextEdit_collectionURL = QtWidgets.QPlainTextEdit(self.group_metaDataApplication)
        self.plainTextEdit_collectionURL.setMinimumSize(QtCore.QSize(0, 50))
        self.plainTextEdit_collectionURL.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhUrlCharactersOnly)
        self.plainTextEdit_collectionURL.setTabChangesFocus(True)
        self.plainTextEdit_collectionURL.setObjectName("plainTextEdit_collectionURL")
        self.gridLayout_19.addWidget(self.plainTextEdit_collectionURL, 2, 1, 1, 1)
        self.gridLayout_19.setColumnStretch(1, 3)
        self.verticalLayout_2.addWidget(self.group_metaDataApplication)
        self.groupBox_themes = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_themes.setObjectName("groupBox_themes")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_themes)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.value_DarkTheme = QtWidgets.QRadioButton(self.groupBox_themes)
        self.value_DarkTheme.setChecked(True)
        self.value_DarkTheme.setObjectName("value_DarkTheme")
        self.verticalLayout_5.addWidget(self.value_DarkTheme)
        self.value_LightTheme = QtWidgets.QRadioButton(self.groupBox_themes)
        self.value_LightTheme.setObjectName("value_LightTheme")
        self.verticalLayout_5.addWidget(self.value_LightTheme)
        self.label_23 = QtWidgets.QLabel(self.groupBox_themes)
        self.label_23.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.verticalLayout_2.addWidget(self.groupBox_themes)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.pushButton_resetSettings = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_resetSettings.setObjectName("pushButton_resetSettings")
        self.horizontalLayout_4.addWidget(self.pushButton_resetSettings)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.preferences_ScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.preferences_ScrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.settingsTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_3.setBuddy(self.label_3)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.gridTabWidget_sessionMonitor.setCurrentIndex(0)
        self.comboBox_bcBackend.setCurrentIndex(1)
        self.comboBox_dupNamingPolicy.currentIndexChanged['QString'].connect(MainWindow.saveSettings)
        self.comboBox_colorCheckerPosition.currentTextChanged['QString'].connect(MainWindow.saveSettings)
        self.group_verifyRotation.toggled['bool'].connect(MainWindow.saveSettings)
        self.checkBox_performWhiteBalance.toggled['bool'].connect(MainWindow.saveSettings)
        self.checkBox_lensCorrection.toggled['bool'].connect(MainWindow.saveSettings)
        self.checkBox_metaDataApplication.toggled['bool'].connect(MainWindow.saveSettings)
        self.plainTextEdit_collectionName.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_collectionURL.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_contactName.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_contactEmail.textChanged.connect(MainWindow.saveSettings)
        self.plainTextEdit_copywriteLicense.textChanged.connect(MainWindow.saveSettings)
        self.group_keepUnalteredRaw.toggled['bool'].connect(MainWindow.saveSettings)
        self.group_saveProcessedJpg.toggled['bool'].connect(MainWindow.saveSettings)
        self.group_saveProcessedTIFF.toggled['bool'].connect(MainWindow.saveSettings)
        self.group_saveProcessedPng.toggled['bool'].connect(MainWindow.saveSettings)
        self.lineEdit_inputPath.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathUnalteredRaw.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathProcessedJpg.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathProcessedTIFF.textChanged['QString'].connect(MainWindow.saveSettings)
        self.lineEdit_pathProcessedPng.textChanged['QString'].connect(MainWindow.saveSettings)
        self.pushButton_inputPath.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathUnalteredRaw.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathProcessedJpg.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathProcessedTIFF.clicked.connect(MainWindow.setFolderPath)
        self.pushButton_pathProcessedPng.clicked.connect(MainWindow.setFolderPath)
        self.lineEdit_catalogNumberPrefix.editingFinished.connect(MainWindow.updateCatalogNumberPreviews)
        self.spinBox_catalogDigits.editingFinished.connect(MainWindow.updateCatalogNumberPreviews)
        self.comboBox_dupNamingPolicy.currentIndexChanged['QString'].connect(MainWindow.updateCatalogNumberPreviews)
        self.pushButton_selectTestImage.clicked.connect(MainWindow.testFeatureCompatability)
        self.group_renameByBarcode.toggled['bool'].connect(MainWindow.updateCatalogNumberPreviews)
        self.doubleSpinBox_focalDistance.editingFinished.connect(MainWindow.saveSettings)
        self.checkBox_blurDetection.toggled['bool'].connect(self.doubleSpinBox_blurThreshold.setEnabled)
        self.checkBox_blurDetection.toggled['bool'].connect(self.label_13.setEnabled)
        self.radioButton_colorCheckerLarge.toggled['bool'].connect(MainWindow.saveSettings)
        self.radioButton_colorCheckerSmall.toggled['bool'].connect(MainWindow.saveSettings)
        self.toolButton_addPattern.clicked.connect(MainWindow.saveSettings)
        self.toolButton_removePattern.clicked.connect(MainWindow.saveSettings)
        self.pushButton_resetSettings.clicked.connect(MainWindow.reset_all_settings)
        self.comboBox_bcBackend.currentTextChanged['QString'].connect(MainWindow.saveSettings)
        self.pushButton_processMulti.clicked.connect(MainWindow.process_image_directory)
        self.pushButton_processSingle.clicked.connect(MainWindow.process_image_selection)
        self.comboBox_technician.currentTextChanged['QString'].connect(MainWindow.update_metadata)
        self.lineEdit_taxonName.textEdited['QString'].connect(MainWindow.update_metadata)
        self.lineEdit_collectorName.textChanged['QString'].connect(MainWindow.update_metadata)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_inputPath, self.pushButton_inputPath)
        MainWindow.setTabOrder(self.pushButton_inputPath, self.group_keepUnalteredRaw)
        MainWindow.setTabOrder(self.group_keepUnalteredRaw, self.lineEdit_pathUnalteredRaw)
        MainWindow.setTabOrder(self.lineEdit_pathUnalteredRaw, self.pushButton_pathUnalteredRaw)
        MainWindow.setTabOrder(self.pushButton_pathUnalteredRaw, self.lineEdit_pathProcessedTIFF)
        MainWindow.setTabOrder(self.lineEdit_pathProcessedTIFF, self.pushButton_pathProcessedTIFF)
        MainWindow.setTabOrder(self.pushButton_pathProcessedTIFF, self.lineEdit_pathProcessedJpg)
        MainWindow.setTabOrder(self.lineEdit_pathProcessedJpg, self.pushButton_pathProcessedJpg)
        MainWindow.setTabOrder(self.pushButton_pathProcessedJpg, self.lineEdit_pathProcessedPng)
        MainWindow.setTabOrder(self.lineEdit_pathProcessedPng, self.pushButton_pathProcessedPng)
        MainWindow.setTabOrder(self.pushButton_pathProcessedPng, self.preferences_ScrollArea)
        MainWindow.setTabOrder(self.preferences_ScrollArea, self.group_barcodeDetection)
        MainWindow.setTabOrder(self.group_barcodeDetection, self.group_renameByBarcode)
        MainWindow.setTabOrder(self.group_renameByBarcode, self.group_colorCheckerDetection)
        MainWindow.setTabOrder(self.group_colorCheckerDetection, self.group_verifyRotation)
        MainWindow.setTabOrder(self.group_verifyRotation, self.checkBox_performWhiteBalance)
        MainWindow.setTabOrder(self.checkBox_performWhiteBalance, self.group_equipmentDetection)
        MainWindow.setTabOrder(self.group_equipmentDetection, self.plainTextEdit_collectionName)
        MainWindow.setTabOrder(self.plainTextEdit_collectionName, self.plainTextEdit_copywriteLicense)
        MainWindow.setTabOrder(self.plainTextEdit_copywriteLicense, self.monitor_scrollArea)
        MainWindow.setTabOrder(self.monitor_scrollArea, self.plainTextEdit_contactEmail)
        MainWindow.setTabOrder(self.plainTextEdit_contactEmail, self.plainTextEdit_contactName)
        MainWindow.setTabOrder(self.plainTextEdit_contactName, self.plainTextEdit_collectionURL)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_35.setText(_translate("MainWindow", "Process time:"))
        self.label_22.setText(_translate("MainWindow", "Barcodes:"))
        self.label_18.setText(_translate("MainWindow", "Is blurry:"))
        self.label_21.setText(_translate("MainWindow", "Norm. Laplacian:"))
        self.label_17.setText(_translate("MainWindow", "(higher is better)"))
        self.label_24.setText(_translate("MainWindow", "CC runtime:"))
        self.label_20.setText(_translate("MainWindow", "CC white rgb:"))
        self.formGroupBox_sessionMetadata.setTitle(_translate("MainWindow", "Apply Session Metadata"))
        self.label_16.setText(_translate("MainWindow", "Taxon:"))
        self.label_19.setText(_translate("MainWindow", "Collector:"))
        self.label_14.setText(_translate("MainWindow", "Technician:"))
        self.toolButton_editTechnicians.setText(_translate("MainWindow", "..."))
        self.label_rate.setText(_translate("MainWindow", "0.00"))
        self.label_32.setText(_translate("MainWindow", "Rate (per min)"))
        self.label_29.setText(_translate("MainWindow", "Session Minutes"))
        self.label_runTime.setText(_translate("MainWindow", "0.00"))
        self.label_imgCount.setText(_translate("MainWindow", "0"))
        self.label_31.setText(_translate("MainWindow", "Image Count"))
        self.pushButton_toggleMonitoring.setText(_translate("MainWindow", "Begin Monitoring Folder"))
        self.gridTabWidget_sessionMonitor.setTabText(self.gridTabWidget_sessionMonitor.indexOf(self.gridTabWidget_sessionSelect), _translate("MainWindow", "Monitor Folder"))
        self.pushButton_processMulti.setText(_translate("MainWindow", "Process Entire Directory"))
        self.pushButton_processSingle.setText(_translate("MainWindow", "Process Select Image(s)"))
        self.gridTabWidget_sessionMonitor.setTabText(self.gridTabWidget_sessionMonitor.indexOf(self.tab), _translate("MainWindow", "Select Image(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.folderMonitorTab), _translate("MainWindow", "Process Images"))
        self.group_inputSettings.setTitle(_translate("MainWindow", "Input settings"))
        self.label_6.setText(_translate("MainWindow", "Folder"))
        self.pushButton_inputPath.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Input folder path (the location to monitor for newly captured photos)"))
        self.group_keepUnalteredRaw.setTitle(_translate("MainWindow", "Move unaltered original images after processing"))
        self.label_7.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathUnalteredRaw.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Destination folder path (the location to save unprocessed archive format images)"))
        self.group_saveProcessedJpg.setTitle(_translate("MainWindow", "Save processed Images as JPG"))
        self.label_9.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathProcessedJpg.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "Destination folder path (the location to save processed images as JPG files)"))
        self.group_saveProcessedTIFF.setTitle(_translate("MainWindow", "Save processed Images as TIFF"))
        self.label_8.setText(_translate("MainWindow", "Folder"))
        self.pushButton_pathProcessedTIFF.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Destination folder path (the location to save processed images as TIFF files)"))
        self.group_saveProcessedPng.setTitle(_translate("MainWindow", "Save processed Images as PNG"))
        self.pushButton_pathProcessedPng.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "Folder"))
        self.label_12.setText(_translate("MainWindow", "Destination folder path (the location to save processed images as PNG files)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imgPathsTab), _translate("MainWindow", "Image Paths"))
        self.label.setText(_translate("MainWindow", "Test feature compatability"))
        self.pushButton_selectTestImage.setText(_translate("MainWindow", "Select test image"))
        self.group_barcodeDetection.setTitle(_translate("MainWindow", "Barcode detection"))
        self.group_renameByBarcode.setTitle(_translate("MainWindow", "Rename images by barcode number"))
        self.label_digits.setText(_translate("MainWindow", "Digits"))
        self.lineEdit_catalogNumberPrefix.setPlaceholderText(_translate("MainWindow", "ABCD"))
        self.label_25.setText(_translate("MainWindow", "Decoder backend "))
        self.label_dupNamingPolicy.setText(_translate("MainWindow", "Duplicate naming policy"))
        self.label_dupPreview.setText(_translate("MainWindow", "Preview"))
        self.comboBox_bcBackend.setItemText(0, _translate("MainWindow", "libdmtx"))
        self.comboBox_bcBackend.setItemText(1, _translate("MainWindow", "zbar"))
        self.label_catalogNumberPrefix.setText(_translate("MainWindow", "Catalog Number Prefix"))
        self.comboBox_dupNamingPolicy.setItemText(0, _translate("MainWindow", "LOWER case letter"))
        self.comboBox_dupNamingPolicy.setItemText(1, _translate("MainWindow", "UPPER case letter"))
        self.comboBox_dupNamingPolicy.setItemText(2, _translate("MainWindow", "Number with underscore"))
        self.comboBox_dupNamingPolicy.setItemText(3, _translate("MainWindow", "OVERWRITE original"))
        self.toolButton_removePattern.setText(_translate("MainWindow", "remove"))
        self.toolButton_addPattern.setText(_translate("MainWindow", "add "))
        self.label_28.setText(_translate("MainWindow", "barcode regex patterns"))
        self.group_blurDetection.setTitle(_translate("MainWindow", "Blur detection"))
        self.label_15.setText(_translate("MainWindow", "(lower is more blur tolerant)"))
        self.checkBox_blurDetection.setText(_translate("MainWindow", "Check images for blur"))
        self.label_13.setText(_translate("MainWindow", "Laplacian threshold"))
        self.group_colorCheckerDetection.setTitle(_translate("MainWindow", "Color checker detection"))
        self.groupBox_colorCheckerSize.setTitle(_translate("MainWindow", "Color checker size"))
        self.radioButton_colorCheckerSmall.setText(_translate("MainWindow", "Small"))
        self.radioButton_colorCheckerLarge.setText(_translate("MainWindow", "Large"))
        self.group_verifyRotation.setTitle(_translate("MainWindow", "Verify image rotation using color checker position"))
        self.comboBox_colorCheckerPosition.setItemText(0, _translate("MainWindow", "Upper right"))
        self.comboBox_colorCheckerPosition.setItemText(1, _translate("MainWindow", "Lower right"))
        self.comboBox_colorCheckerPosition.setItemText(2, _translate("MainWindow", "Lower left"))
        self.comboBox_colorCheckerPosition.setItemText(3, _translate("MainWindow", "Upper left"))
        self.label_colorCheckerPosition.setText(_translate("MainWindow", "Color checker Position"))
        self.checkBox_performWhiteBalance.setText(_translate("MainWindow", "Perform white balance using color checker"))
        self.group_equipmentDetection.setTitle(_translate("MainWindow", "Equipment detection"))
        self.label_2.setText(_translate("MainWindow", "Approximate focal distance"))
        self.doubleSpinBox_focalDistance.setSuffix(_translate("MainWindow", "cm"))
        self.checkBox_lensCorrection.setText(_translate("MainWindow", "Perform Lens corrections"))
        self.group_metaDataApplication.setTitle(_translate("MainWindow", "Metadata application"))
        self.label_copywriteLicense.setText(_translate("MainWindow", "Copywrite License:"))
        self.label_collectionName.setText(_translate("MainWindow", "Collection name:"))
        self.label_contactEmail.setText(_translate("MainWindow", "Contact Email:"))
        self.label_collectionIURL.setText(_translate("MainWindow", "Collection URL:"))
        self.label_contactName.setText(_translate("MainWindow", "Contact name:"))
        self.checkBox_metaDataApplication.setText(_translate("MainWindow", "Apply metadata to images"))
        self.groupBox_themes.setTitle(_translate("MainWindow", "Theme"))
        self.value_DarkTheme.setText(_translate("MainWindow", "Dark theme"))
        self.value_LightTheme.setText(_translate("MainWindow", "Default System Settings"))
        self.label_23.setText(_translate("MainWindow", "(changes will be applied the next time the program opens)"))
        self.pushButton_resetSettings.setText(_translate("MainWindow", "Reset ALL Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
from . import assets_rc
